In [3]:
import numpy as np

**1) Create Two numpy array of size 3 X 2 and 2 X 3**

**2) Randomly Initalize that array**

In [8]:
arr1 = np.random.randint( 10, size=(3, 2) )
arr2 = np.random.randint( 10, size=(2, 3) )

print(arr1)
print(arr2)

[[1 6]
 [9 4]
 [1 4]]
[[7 0 1]
 [6 1 5]]


**3) Perform matrix multiplication**

In [13]:
arr_mul = np.dot(arr1, arr2)
#arr_mul = np.matmul(arr1, arr2)

print(arr_mul)

[[43  6 31]
 [87  4 29]
 [31  4 21]]


**4) Perform elementwise matrix multiplication**

In [16]:
#Transpose of arr2 because both matrix should have same dimensions
t_arr2 = arr2.T

arr_mul_elmnt = np.multiply( arr1, t_arr2 )

print( arr_mul_elmnt )

[[ 7 36]
 [ 0  4]
 [ 1 20]]


**5) Find mean of first matrix**

In [17]:
arr1_mean = np.mean(arr1) 

print( arr1_mean )

4.166666666666667


**6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version**

In [18]:
import pandas as pd

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [25]:
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ML-Lab/L1/mtcars.csv')
d = pd.crosstab( index = data['cyl'], columns="count", dropna=True )
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB
None


In [67]:
feat_dict = dict()

for key, value in data.items():
  if key != 'model':
    value = [int(i) for i in value]
  feat_dict[key] = value

feat_dict.pop('model')

for key, value in feat_dict.items():
  value = value - np.mean( value )
  feat_dict[key] = list(value)

feat_dict

{'am': [0.59375,
  0.59375,
  0.59375,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  0.59375,
  0.59375,
  0.59375,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  -0.40625,
  0.59375,
  0.59375,
  0.59375,
  0.59375,
  0.59375,
  0.59375,
  0.59375],
 'carb': [1.1875,
  1.1875,
  -1.8125,
  -1.8125,
  -0.8125,
  -1.8125,
  1.1875,
  -0.8125,
  -0.8125,
  1.1875,
  1.1875,
  0.1875,
  0.1875,
  0.1875,
  1.1875,
  1.1875,
  1.1875,
  -1.8125,
  -0.8125,
  -1.8125,
  -1.8125,
  -0.8125,
  -0.8125,
  1.1875,
  -0.8125,
  -1.8125,
  -0.8125,
  -0.8125,
  1.1875,
  3.1875,
  5.1875,
  -0.8125],
 'cyl': [-0.1875,
  -0.1875,
  -2.1875,
  -0.1875,
  1.8125,
  -0.1875,
  1.8125,
  -2.1875,
  -2.1875,
  -0.1875,
  -0.1875,
  1.8125,
  1.8125,
  1.8125,
  1.8125,
  1.8125,
  1.8125,
  -2.1875,
  -2.1875,
  -2.1875,
  -2.1875,
  1.8125,
  1.8125,
  1.8125,
  1.8125,
  -2.1